# This is a basic workflow to help you get started with Actions

name: Linters and Tests

# Controls when the workflow will run
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - '**'

env:
  FORCE_COLOR: 2

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: node:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Check linting
        run: npm run lint

      - name: Run Tests
        run: npm run test
